# Convert table to adjacency matrix

In [16]:

import pandas as pd
import numpy as np

city_distances = pd.read_csv("../data/city_distances.csv")

## Drive distance Adjacency Matrix

In [17]:
# Get unique cities
cities = pd.concat([city_distances['from'], city_distances['to']]).unique()

# Create an empty adjacency matrix
drive_distance_adj_mat = pd.DataFrame(np.inf, index=cities, columns=cities)

# Fill the adjacency matrix with distances
for _, row in city_distances.iterrows():
    drive_distance_adj_mat.at[row['from'], row['to']] = row['distance_km']
    drive_distance_adj_mat.at[row['to'], row['from']] = row['distance_km']  

# Replace inf with 0 for cities referencing themselves
drive_distance_adj_mat.replace(np.inf, 0, inplace=True)

display(drive_distance_adj_mat)

,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,Cridersville,Delphos,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
Ada,0.00,8.81,19.50,31.26,102.21,66.05,36.16,70.66,38.76,51.03,...,47.60,60.42,35.75,78.84,69.13,49.06,68.87,53.51,50.39,34.99
Alger,8.81,0.00,28.23,39.99,110.94,74.77,44.89,79.39,36.16,59.76,...,56.32,69.15,37.78,79.45,66.54,47.56,77.59,62.23,47.79,26.20
Bluffton,19.50,28.23,0.00,23.98,108.65,54.80,16.28,52.79,39.32,43.75,...,29.64,53.14,11.84,123.45,69.69,49.64,73.77,59.95,50.95,45.47
Cairo,31.26,39.99,23.98,0.00,120.01,77.80,11.23,45.06,22.97,23.50,...,22.42,32.89,20.32,134.81,54.43,36.03,86.67,71.31,35.69,34.18
Caledonia,102.21,110.94,108.65,120.01,0.00,65.92,125.46,159.95,139.46,140.33,...,127.54,149.72,125.04,34.65,169.84,152.85,62.22,43.64,151.10,91.43
Carey,66.05,74.77,54.80,77.80,65.92,0.00,67.61,89.80,93.50,97.94,...,66.65,107.33,58.74,79.47,123.88,103.82,18.97,20.77,105.13,99.65
Columbus Grove,36.16,44.89,16.28,11.23,125.46,67.61,0.00,34.18,32.72,33.25,...,11.54,27.47,9.09,139.75,64.19,45.78,91.61,76.25,45.44,43.93
Continental,70.66,79.39,52.79,45.06,159.95,89.80,34.18,0.00,59.48,34.81,...,23.17,25.75,39.26,174.55,70.65,50.27,108.34,111.05,72.20,71.16
Cridersville,38.76,36.16,39.32,22.97,139.46,93.50,32.72,59.48,0.00,39.94,...,43.93,49.32,43.07,127.13,34.60,24.69,104.21,88.85,15.85,21.72
Delphos,51.03,59.76,43.75,23.50,140.33,97.94,33.25,34.81,39.94,0.00,...,44.30,11.65,42.21,155.16,36.52,16.14,107.02,91.66,37.55,51.84
Dunkirk,17.85,26.58,32.17,43.53,86.25,49.33,48.47,83.27,61.07,63.88,...,60.01,72.84,48.16,70.02,92.96,75.98,53.06,37.70,74.22,49.74
Elida,44.79,37.16,37.51,15.13,134.09,91.70,24.89,49.64,21.05,13.38,...,36.10,24.12,36.72,149.39,52.52,19.58,101.25,85.89,25.72,33.07
Forest,35.97,44.70,42.41,53.77,73.30,36.38,58.72,93.52,71.32,74.12,...,70.17,83.00,58.32,58.01,103.12,86.13,40.14,24.78,84.38,53.08
Fort Jennings,57.86,66.59,50.58,30.33,147.15,104.76,22.91,25.76,46.76,9.33,...,27.46,4.71,32.00,161.98,45.18,24.80,113.84,98.48,46.21,58.67
Glandorf,50.50,59.23,33.05,25.32,130.96,70.07,14.44,23.59,46.84,35.58,...,3.43,27.44,19.52,154.09,78.28,51.05,88.60,90.59,59.54,58.03
Kalida,52.05,60.77,44.77,23.20,141.34,81.32,21.81,18.61,40.87,21.82,...,14.68,13.68,30.90,155.94,57.67,37.29,107.80,92.44,53.59,52.55
Kenton,24.99,25.59,48.18,59.54,57.86,55.46,64.49,99.29,55.66,79.89,...,76.03,88.85,64.18,53.99,72.92,66.97,59.22,38.72,55.37,33.70
La Rue,52.09,52.69,73.67,85.03,39.92,52.66,89.97,124.77,82.76,105.37,...,101.42,114.25,89.58,28.56,100.02,94.06,50.88,33.19,82.47,60.80
Leipsic,48.76,57.49,30.69,34.72,125.78,64.88,23.84,25.23,61.36,56.61,...,12.83,40.67,18.52,139.96,92.05,69.27,83.42,81.26,73.30,67.82
Lima,26.28,25.64,26.86,11.65,127.00,81.04,21.40,48.63,11.81,29.31,...,32.80,38.66,30.57,139.86,44.68,22.87,91.72,76.36,25.93,22.62
Marion,91.69,68.17,98.14,109.49,15.56,54.16,114.44,149.24,127.04,129.84,...,116.95,139.13,114.46,17.08,159.26,142.27,51.63,33.06,140.51,77.28
Minster,84.84,82.24,85.40,70.14,185.55,139.59,79.89,87.63,50.30,53.49,...,90.58,65.15,89.00,129.33,17.04,37.35,150.15,134.79,36.13,57.37
Mount Victory,39.74,40.34,63.06,74.42,59.53,70.12,79.36,114.16,70.41,94.77,...,90.90,103.73,79.06,38.11,82.11,81.71,73.88,53.38,64.55,47.19
Nevada,71.70,80.43,78.14,89.50,39.98,34.17,94.45,129.25,107.05,109.85,...,97.25,119.42,94.75,54.35,139.55,122.56,17.86,16.56,120.80,103.71
New Bremen,79.50,76.90,80.06,64.80,180.20,134.24,74.55,82.72,44.96,48.59,...,85.26,60.25,83.68,124.34,12.14,32.45,144.83,129.47,31.23,52.05
New Knoxville,69.38,66.79,69.94,54.68,170.09,124.13,64.44,79.73,34.85,45.59,...,74.75,57.25,73.17,125.23,10.18,29.45,134.32,118.96,19.22,41.49
Ottawa,47.60,56.32,29.64,22.42,127.54,66.65,11.54,23.17,43.93,44.30,...,0.00,28.36,16.10,141.73,75.38,56.97,85.18,87.68,56.63,55.12
Ottoville,60.42,69.15,53.14,32.89,149.72,107.33,27.47,25.75,49.32,11.65,...,28.36,0.00,36.56,164.26,48.18,27.80,116.12,100.76,61.98,60.94
Pandora,35.75,37.78,11.84,20.32,125.04,58.74,9.09,39.26,43.07,42.21,...,16.10,36.56,0.00,137.83,73.75,53.69,89.69,74.33,55.00,49.52
Prospect,78.84,79.45,123.45,134.81,34.65,79.47,139.75,174.55,127.13,155.16,...,141.73,164.26,137.83,0.00,134.56,167.31,76.68,58.10,117.01,102.95
Saint Marys,69.13,66.54,69.69,54.43,169.84,123.88,64.19,70.65,34.60,36.52,...,75.38,48.18,73.75,134.56,0.00,20.38,134.25,118.89,19.16,41.43
Spencerville,49.06,47.56,49.64,36.03,152.85,103.82,45.78,50.27,24.69,16.14,...,56.97,27.80,53.69,167.31,20.38,0.00,119.48,104.12,24.47,41.59
Sycamore,68.87,77.59,73.77,86.67,62.22,18.97,91.61,108.34,104.21,107.02,...,85.18,116.12,89.69,76.68,134.25,119.48,0.00,17.74,117.81,100.72
Upper Sandusky,53.51,62.23,59.95,71.31,43.64,20.77,76.25,111.05,88.85,91.66,...,87.68,100.76,74.33,58.10,118.89,104.12,17.74,0.00,102.16,85.06
Wapakoneta,50.39,47.79,50.95,35.69,151.10,105.13,45.44,72.20,15.85,37.55,...,56.63,61.98,55.00,117.01,19.16,24.47,117.81,102.16,0.00,24.62
Waynesfield,34.99,26.20,45.47,34.18,91.43,99.65,43.93,71.16,21.72,51.84,...,55.12,60.94,49.52,102.95,41.43,41.59,100.72,85.06,24.62,0.00

## Drive time Adjacency Matrix

In [18]:
# Get unique cities
cities = pd.concat([city_distances['from'], city_distances['to']]).unique()

# Create an empty adjacency matrix
drive_time_adj_mat = pd.DataFrame(np.inf, index=cities, columns=cities)

# Fill the adjacency matrix with distances
for _, row in city_distances.iterrows():
    drive_time_adj_mat.at[row['from'], row['to']] = row['duration_min']
    drive_time_adj_mat.at[row['to'], row['from']] = row['duration_min']  

# Replace inf with 0 for cities referencing themselves
drive_time_adj_mat.replace(np.inf, 0, inplace=True)
 
display(drive_time_adj_mat)

,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,Cridersville,Delphos,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
Ada,0.00,9.30,20.48,23.63,70.40,45.55,31.78,62.73,35.73,35.74,...,41.59,42.32,31.00,72.88,51.50,50.39,51.19,38.63,39.70,32.14
Alger,9.30,0.00,29.61,32.76,79.53,54.68,40.91,71.86,36.43,44.88,...,50.72,51.45,37.84,73.76,52.20,51.39,60.32,47.76,40.39,22.95
Bluffton,20.48,29.61,0.00,18.42,76.23,36.78,20.55,49.98,29.81,30.53,...,26.52,37.11,15.30,84.11,45.58,45.18,56.07,44.46,33.78,37.66
Cairo,23.63,32.76,18.42,0.00,78.76,51.34,11.29,42.34,26.10,17.40,...,19.81,23.98,20.73,86.64,43.96,32.74,59.54,46.98,32.15,37.08
Caledonia,70.40,79.53,76.23,78.76,0.00,47.25,87.77,118.71,95.99,91.73,...,96.46,98.31,86.98,28.59,111.76,107.07,49.45,34.24,99.96,90.16
Carey,45.55,54.68,36.78,51.34,47.25,0.00,57.96,78.84,63.76,64.48,...,55.38,71.06,48.79,53.68,79.53,79.13,19.29,15.77,67.73,71.61
Columbus Grove,31.78,40.91,20.55,11.29,87.77,57.96,0.00,32.45,35.78,27.08,...,9.92,28.86,9.43,94.52,53.64,42.42,67.42,54.87,41.84,46.76
Continental,62.73,71.86,49.98,42.34,118.71,78.84,32.45,0.00,63.28,36.13,...,23.51,26.32,41.28,126.22,74.44,52.23,97.36,86.57,69.34,74.72
Cridersville,35.73,36.43,29.81,26.10,95.99,63.76,35.78,63.28,0.00,36.77,...,44.46,43.35,35.31,101.02,28.29,30.89,74.39,61.84,16.48,27.29
Delphos,35.74,44.88,30.53,17.40,91.73,64.48,27.08,36.13,36.77,0.00,...,35.47,10.96,36.38,99.67,39.11,16.90,72.58,60.02,39.91,48.70
Dunkirk,18.74,27.87,26.69,29.21,59.40,33.70,37.09,68.80,44.07,42.25,...,47.69,48.42,37.10,64.92,61.88,57.18,40.22,27.67,50.07,50.14
Elida,35.72,39.09,30.50,17.23,91.70,64.45,26.91,47.81,24.93,14.07,...,35.59,21.85,36.18,100.05,42.63,22.80,72.96,60.40,30.52,36.73
Forest,27.32,36.46,33.15,35.68,51.67,25.98,43.56,75.27,50.53,48.72,...,53.77,54.51,43.18,55.06,67.96,63.27,32.69,20.14,56.16,53.77
Fort Jennings,43.19,52.32,37.97,24.84,99.17,71.92,24.18,26.77,44.21,10.26,...,28.09,5.28,33.62,107.12,48.57,26.36,80.02,67.47,49.38,56.14
Glandorf,45.77,54.89,31.63,23.99,101.58,60.49,14.10,24.74,48.64,36.88,...,5.16,27.83,22.93,108.50,66.33,52.98,79.01,68.85,54.53,59.46
Kalida,43.13,52.26,37.91,24.30,99.11,70.10,22.78,19.60,43.68,22.69,...,14.77,13.63,32.21,106.62,61.00,38.79,79.52,66.97,49.73,55.12
Kenton,24.45,25.33,42.95,45.47,56.63,45.61,53.35,85.06,54.52,58.51,...,63.95,64.68,53.36,48.70,64.04,69.76,52.32,39.59,52.98,33.80
La Rue,50.69,51.56,66.02,68.55,40.17,50.21,76.42,108.13,80.76,81.58,...,86.64,87.38,76.05,25.93,90.28,96.00,52.56,34.57,79.21,60.03
Leipsic,48.20,57.33,29.78,32.32,96.62,55.53,22.43,25.95,56.94,47.98,...,13.49,40.91,21.90,103.90,73.64,63.45,74.05,65.99,61.84,65.72
Lima,26.32,28.07,21.10,12.31,87.28,55.05,22.00,49.95,14.94,23.93,...,30.99,30.34,26.80,92.98,32.44,24.60,65.89,53.33,20.63,25.35
Marion,63.48,65.53,69.31,71.84,15.84,38.88,79.71,111.42,86.69,84.87,...,89.53,91.37,80.04,16.59,104.82,100.13,42.51,27.31,93.02,75.64
Minster,67.17,67.87,61.26,59.63,127.44,95.21,69.31,92.29,43.96,56.95,...,77.11,67.86,66.60,103.18,18.00,40.06,105.68,93.12,32.90,48.83
Mount Victory,39.20,40.07,57.87,60.39,59.07,60.28,68.27,99.98,69.27,73.43,...,78.87,79.61,68.28,34.67,73.98,84.51,67.00,54.27,62.92,46.77
Nevada,48.33,57.46,54.16,56.68,36.09,23.73,64.56,96.27,71.53,69.72,...,74.23,76.08,64.75,43.25,89.53,84.84,18.97,13.53,77.72,79.89
New Bremen,61.95,62.65,56.04,54.41,122.22,89.99,64.09,87.17,38.74,51.83,...,72.05,62.74,61.54,97.95,12.88,34.94,100.62,88.07,27.77,43.77
New Knoxville,56.91,57.61,51.00,49.37,117.17,84.95,59.05,84.40,33.70,49.07,...,66.84,59.98,56.33,99.92,11.83,32.17,95.41,82.86,19.68,38.06
Ottawa,41.59,50.72,26.52,19.81,96.46,55.38,9.92,23.51,44.46,35.47,...,0.00,28.40,17.82,103.75,62.16,50.94,73.90,64.67,50.35,55.28
Ottoville,42.32,51.45,37.11,23.98,98.31,71.06,28.86,26.32,43.35,10.96,...,28.40,0.00,38.29,105.71,50.02,27.80,78.62,66.06,49.36,54.74
Pandora,31.00,37.84,15.30,20.73,86.98,48.79,9.43,41.28,35.31,36.38,...,17.82,38.29,0.00,92.56,52.01,51.61,65.46,52.90,40.21,44.09
Prospect,72.88,73.76,84.11,86.64,28.59,53.68,94.52,126.22,101.02,99.67,...,103.75,105.71,92.56,0.00,102.56,114.42,56.80,41.60,91.50,80.23
Saint Marys,51.50,52.20,45.58,43.96,111.76,79.53,53.64,74.44,28.29,39.11,...,62.16,50.02,52.01,102.56,0.00,22.21,90.79,78.23,15.05,33.43
Spencerville,50.39,51.39,45.18,32.74,107.07,79.13,42.42,52.23,30.89,16.90,...,50.94,27.80,51.61,114.42,22.21,0.00,87.72,75.16,25.43,45.41
Sycamore,51.19,60.32,56.07,59.54,49.45,19.29,67.42,97.36,74.39,72.58,...,73.90,78.62,65.46,56.80,90.79,87.72,0.00,18.05,80.92,83.08
Upper Sandusky,38.63,47.76,44.46,46.98,34.24,15.77,54.87,86.57,61.84,60.02,...,64.67,66.06,52.90,41.60,78.23,75.16,18.05,0.00,67.50,69.67
Wapakoneta,39.70,40.39,33.78,32.15,99.96,67.73,41.84,69.34,16.48,39.91,...,50.35,49.36,40.21,91.50,15.05,25.43,80.92,67.50,0.00,21.86
Waynesfield,32.14,22.95,37.66,37.08,90.16,71.61,46.76,74.72,27.29,48.70,...,55.28,54.74,44.09,80.23,33.43,45.41,83.08,69.67,21.86,0.00

## Save into new CSVs

In [19]:
drive_distance_adj_mat.to_csv("../data/adjacencyMatrixDist.csv")
drive_time_adj_mat.to_csv("../data/adjacencyMatrixTravelTime.csv")