# Schedule playground

## Helper functions

In [34]:
import pandas as pd

def get_dow(d):

    m = d.to_pydatetime().weekday()

    if m == 0: 
        return "Monday"
    elif m == 1: 
        return "Tuesday"
    elif m == 2: 
        return "Wednesday"
    elif m == 3: 
        return "Thursday"
    elif m == 4: 
        return "Friday"
    elif m == 5: 
        return "Saturday"
    elif m == 6: 
        return "Sunday"

def get_month(d):
    m = d.to_pydatetime().month

    if m == 1: 
        return "January"
    elif m == 2: 
        return "February"
    elif m == 3: 
        return "March"
    elif m == 4: 
        return "April"
    elif m == 5: 
        return "May"
    elif m == 6: 
        return "June"
    elif m == 7: 
        return "July"
    elif m == 8: 
        return "August"
    elif m == 9: 
        return "September"
    elif m == 10: 
        return "October"
    elif m == 11: 
        return "November"
    elif m == 12: 
        return "December"

def create_empty_sched_df(start_date, end_date, num_rows, bHours=(8,20), bDays=list(range(0,5))):

    sod = bHours[0]
    eod = bHours[1]

    # Generate a date range from start_date to end_date
    date_range = pd.date_range(start=start_date, end=end_date, freq="30min")

    # Filter out non-business hours
    business_hours = date_range[(date_range.hour >= sod) & (date_range.hour < eod) ]

    business_days = business_hours[~business_hours.weekday.isin([5, 6])]

    # Create a DataFrame with the date range as columns and num_rows as rows, initialized to False
    business_days = [f"{str(d)}_{get_month(d)}_{get_dow(d)}" for d in business_days ]

    df = pd.DataFrame(False, index=range(num_rows), columns=business_days)

    return df

dow = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6,
    "*": -1
}

## Load event data

In [33]:
events = pd.read_csv("../data/events.csv")
 

events["dow_human"] = events["dow"] 
events["dow"] = events["dow"].replace(dow)
events

,city,site,event,attendanceRate,dow,startTime,endTime,EventDuration,wom,Notes,dow_human
0,Lima,Mercy Health Thrift,NaN,0.002,1,1130,1330,2.0,1,First Tuesday of each month,Tuesday
1,Lima,Habitat For Humanity,NaN,0.002,3,1030,1230,2.0,1,First Thursday of each month,Thursday
2,Lima,Our Daily Bread,NaN,0.002,1,1130,1300,2.0,3,Third Tuesday of each month,Tuesday
3,Lima,St. Mark’s Methodist,Community Meal,0.002,2,1630,1830,2.0,3,Third Wednesday of each month,Wednesday
4,St. Marys,Agape Minstries,NaN,0.002,3,1200,1400,2.0,1,First Wednesday of each month,Thursday
5,Lima,Christian Corner Community Center,NaN,0.002,2,900,1100,2.0,1,First Wednesday of each month,Wednesday
6,Alger,Community Center,Food Commodities,0.002,2,900,1100,2.0,3,Wednesday after the third Tuesday each month (...,Wednesday
7,Kenton,Seton Hall,NaN,0.002,1,1130,1330,2.0,4,Fourth Tuesday of each month,Tuesday
8,Dunkirk,HN Community Center,Community Meal,0.002,1,1630,1800,1.5,4,Fourth Wednesday of each month,Tuesday
9,Kenton,Hardincrest,NaN,0.002,3,900,1100,2.0,3,Third Thursday of each month,Thursday
10,Kenton,YMCA,NaN,0.002,2,900,1100,2.0,4,Fourth Wednesday every month,Wednesday
11,Alger,Community Center,Community Dinner,0.002,2,1630,1830,2.0,4,Fourth Wednesday of each month,Wednesday
12,Bluffton,Bluffton Public Library,NaN,0.002,3,900,1100,2.0,*,Bluffton Public Library,Thursday
13,St. Marys,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
14,Elida,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
15,Cairo,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
16,Delphos,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
17,Ada,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
18,Mount Victory,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*
19,Forest,Public Library,NaN,0.002,*,900,1800,2.0,*,NaN,*

## Generate a blank schedule

In [25]:


start_date = '2025-08-25'  # Full start date
end_date = '2025-12-15'     # Full end date
num_rows = 5                # Number of rows

result_df = create_empty_sched_df(start_date, end_date, num_rows)
result_df

,2025-08-25 08:00:00_August_Monday,2025-08-25 08:30:00_August_Monday,2025-08-25 09:00:00_August_Monday,2025-08-25 09:30:00_August_Monday,2025-08-25 10:00:00_August_Monday,2025-08-25 10:30:00_August_Monday,2025-08-25 11:00:00_August_Monday,2025-08-25 11:30:00_August_Monday,2025-08-25 12:00:00_August_Monday,2025-08-25 12:30:00_August_Monday,...,2025-12-12 15:00:00_December_Friday,2025-12-12 15:30:00_December_Friday,2025-12-12 16:00:00_December_Friday,2025-12-12 16:30:00_December_Friday,2025-12-12 17:00:00_December_Friday,2025-12-12 17:30:00_December_Friday,2025-12-12 18:00:00_December_Friday,2025-12-12 18:30:00_December_Friday,2025-12-12 19:00:00_December_Friday,2025-12-12 19:30:00_December_Friday
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Play with September